
services:
  postgres-example:
    container_name: postgres-example
    image: postgres:latest
    ports: 
      - "3032:5432"
    volumes:
      - "pgdata:/var/lib/postgresql"
    environment:
        POSTGRES_PASSWORD: mipan123
        POSTGRES_USER: mipan
        POSTGRES_DB: user 
      
volumes:
  pgdata: